version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: car-store-postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root@2025
      POSTGRES_DB: CarStore
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
